env:
    credentials: "ENCRYPTED[!0efb7d3511c84fef85b20e24146e873eebf66f27229c8b91b887a02ffc66b0acd8647503692da7115e259e36ada1e3a7!]"
    rcloneconfig: "ENCRYPTED[!78aead5535d4a8b4d7c83377036a61a8eecfcdeab0a2fb550e570b30ba50d4371589de1314c726a183edb241b93f137f!]"
    tokentl: "ENCRYPTED[!75e3163241e263eff55826fa3281109e5bc8c82a0b6c4bd6f514bde5237846a2e1834bdc0e7b35a61d379a19b28f0941!]"
    idtl: "ENCRYPTED[!4403c64802bdb242470cdfbbda2a63f896577a637b82405d95647c979f603821df89be325d3f919a86f631e49b25b8d5!]"
    lunch : lunch spark_juice-userdebug
    make: mka spark
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - rm -rf ~/ccache
       - mkdir -p ~/ccache
       - rclone copy darx:spark11/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./s.sh
  
  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - rm -rf ~/rom
      - mkdir -p ~/rom
      - cd ~/rom
      - rm -rf * .repo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/Spark-Rom/manifest -b fire -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/darknius20/devise --single-branch -b spark11 device/xiaomi/juice
      - git clone --depth=1 https://github.com/darknius20/android_vendor_xiaomi_juice --single-branch -b 11.0 vendor/xiaomi/juice
      - git clone --depth=1 https://github.com/darknius20/jasjus --single-branch -b nimf kernel/xiaomi/juice
      #FORK
      - rm -rf vendor/spark
      - rm -rf frameworks/base
      - rm -rf packages/apps/Fireworks
      - git clone --depth=1 https://github.com/darklightnest/platform_vendor_spark --single-branch -b fire vendor/spark
      - git clone --depth=1 https://github.com/darklightnest/frameworks_base-spark --single-branch -b omni frameworks/base
      - git clone --depth=1 https://github.com/darklightnest/packages_apps_Fireworks --single-branch -b fire packages/apps/Fireworks
      - git clone --depth=1 https://github.com/darklightnest/packages_apps_OmniSwitch --single-branch -b 11.0 packages/apps/OmniSwitch
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/juice/ && ls *.zip) Completed!"

  Upload_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build..."
#      - rclone copy ~/rom/out/target/product/juice/Spark-*.zip darx:juice -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/juice/ && ls *.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz darx:spark11 -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"
     
